### ISSUE TITLE
Decouple from Travis?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/traceme#10]
At the moment, we have things like `#ifdef TRAVIS` in the code, but I think we can generalise this. It's not exactly Travis that we want to be conditional on, but *any* environment that lacks some of the features we want. As a trivial example, we could change to another CI environment and it would probably have similar restrictions. Or, perhaps, Travis will loosen its restrictions in the future, so what "Travis" means might not even be immutable.

Should we therefore change from "check for platform" to "check for feature"?

**Comment by vext01** [comment]
I think eventually, yes.

I think we should re-visit this later when we are sure that this code will work/be useful in the grand scheme of our tracer.

[Side note: As you pointed out in another PR, we'd need to find out a way to do feature checks with Rust. I'm sure we could figure something out if there is no official way.]

**Comment by vext01** [comment]
I've just found in `/usr/include/linux/perf_event.h` the macros `#define PERF_ATTR_SIZE_VER*` which I think we migh be able to use to decide if the perf implementation is new enough. We might be able to use this to decouple from Travis properly.

**Comment by ltratt** [comment]
An interesting question is whether we should do this at compile-time or run-time. There are obvious advantages and disadvantages to both, but I'm not sure how easy or difficult each might be.

**Comment by vext01** [comment]
The C code won't compile with a too old perf, so compile time it is :)

**Comment by ltratt** [comment]
I guess what I mean is: if we compile with a new perf, can the same binary detect an old perf and disable itself?

**Comment by vext01** [comment]
I'm not sure if that would work, since there are ABI differences. There's a struct for configuring perf which has more members if PT is supported.

**Comment by ltratt** [comment]
If that code isn't called at run-time, it doesn't matter.

Anyway, perhaps this is a red herring. I guess what I *really* care about is "could an OS distribution ship a single binary for a given hardware platform and have it work?" I think the answer is probably yes in either case, but I wouldn't mind being sure!

**Comment by vext01** [comment]
> If that code isn't called at run-time, it doesn't matter.

We indeed use this struct at runtime to configure perf and PT.

> Anyway, perhaps this is a red herring. I guess what I really care about is "could an OS distribution ship a single binary for a given hardware platform and have it work?"

Yes, that's my thinking too. And the answer should be yes.

**Comment by ltratt** [comment]
OK, let's keep an eye on that to make sure that the answer is always "yes" :)
