### ISSUE TITLE
Platform abstractions.

### ISSUE THREAD

**Issue by vext01** [softdevteam/traceme#17]
In the long term, we'd like this to work on other systems than linux/perf. Maybe even linux/notperf.

In light of that, we should add platform abstraction before we get too deeply involved.

**Comment by vext01** [comment]
Ideas:

 * Make different backends using Traits.
 * Consider Travis a backend of it's own.
 * The backend we are using now can become the `perf backend`

**Comment by ltratt** [comment]
I suspect conditional compilation, including conditional compilation of modules, will also prove a very effective tactic. In a sense, best practise in making portable C code probably isn't *too* far off the mark here either.

**Comment by vext01** [comment]
Also fixed. See #19
