### ISSUE TITLE
Proper error handling

### ISSUE THREAD

**Issue by vext01** [softdevteam/traceme#3]
If we get to a point where this is definitely useful, we should add proper error handling. Many places in the code panic at the first hint of trouble.

**Comment by ltratt** [comment]
One general comment: it's hard (as in: annoying) to add `Result` types retrospectively, so if you do think you'll need it, you might not want to wait too long...

**Comment by vext01** [comment]
right, i'll bump the priority of this then.

**Comment by vext01** [comment]
Fixed in #11
